version: 3.0.0
services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres
  redis: 
    image: redis:alpine
  api:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres.POSTGRES_USER
      - PGHOST=postgres
      - PGDATABASE=postgres.POSTGRES_DB
      - PGPASSWORD=postgres.POSTGRES_PASSWORD
      - PGPORT=5432
  client:
    stdin_open: true
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:  # mount the client's node_modules to the server
      - ./client:/app
      - /app/node_modules
  worker:
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./worker:/app
  nginx:
    restart: always
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    depends_on:
      - api
      - client
